#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Tue Mar 24 17:22:25 CDT 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/smartscott/AMD/${SIM_VER_XSIM}/data"
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip -prj tb3d_transcoder_vlog.prj"
xvlog --incr --relax -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip -prj tb3d_transcoder_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
