# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds]
# Derive the project root from this script's location (tb3d.runs/synth_1/ -> ../../)
set proj_root [file normalize [file join [file dirname [file normalize [info script]]] "../.."]]
namespace eval ::optrace {
  variable script [file normalize [info script]]
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.flow 0
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 5-699]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcvp1802-lsvc4072-2MP-e-S

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir $proj_root/tb3d.cache/wt [current_project]
set_property parent.project_path $proj_root/tb3d.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vpk180:part0:1.2 [current_project]
set_property ip_output_repo $proj_root/tb3d.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_decode.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_encode.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_transcoder.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_bit_accessor.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_dragonfly_cache.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_state_buffer.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_vector_engine.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_axi_lite_slave.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_dma_controller.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_engine_top.v
  $proj_root/tb3d.srcs/sources_1/imports/rtl/tb3d_pcie_bridge.v
  $proj_root/tb3d.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
add_files $proj_root/tb3d.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_8be5_S05_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_8be5_S03_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_8be5_S04_AXI_rpu_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_8be5_S02_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_8be5_S01_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_8be5_S00_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/par/bd_8be5_MC0_ddrc_0_ip.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0_board.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xdc]
set_property used_in_synthesis false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da_ooc.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_waivers.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_rst_noc_clk_gen_300M_0/design_1_rst_noc_clk_gen_300M_0_board.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_100M_1/design_1_rst_clk_wiz_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/design_1_ooc.xdc]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/bd_8be5_MC0_ddrc_0_phy_ddrmc.elf]
set_property used_in_synthesis false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/nsln/design_1.nts]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/nsln/design_1.nts]
set_property used_in_synthesis false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/nsln/design_1.ncr]
set_property used_in_implementation false [get_files -all $proj_root/tb3d.gen/sources_1/bd/design_1/nsln/design_1.ncr]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc $proj_root/tb3d.srcs/constrs_1/imports/constraints/usr_constraints.xdc
set_property used_in_implementation false [get_files $proj_root/tb3d.srcs/constrs_1/imports/constraints/usr_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental $proj_root/tb3d.srcs/utils_1/imports/synth_1/design_1_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xcvp1802-lsvc4072-2MP-e-S
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
