vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xilinx_vip
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/microblaze_v11_0_16
vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/noc_nmu_sim_v1_0_0
vlib modelsim_lib/msim/noc_hbm_nmu_sim_v1_0_0
vlib modelsim_lib/msim/xlconstant_v1_1_10
vlib modelsim_lib/msim/proc_sys_reset_v5_0_17
vlib modelsim_lib/msim/smartconnect_v1_0
vlib modelsim_lib/msim/axi_infrastructure_v1_1_0
vlib modelsim_lib/msim/axi_register_slice_v2_1_36
vlib modelsim_lib/msim/axi_vip_v1_1_22
vlib modelsim_lib/msim/axi_apb_bridge_v3_0_21
vlib modelsim_lib/msim/versal_cips_ps_vip_v1_0_14
vlib modelsim_lib/msim/cpm4_v1_0_20
vlib modelsim_lib/msim/cpm5_v1_0_20
vlib modelsim_lib/msim/lmb_v10_v3_0_16
vlib modelsim_lib/msim/lmb_bram_if_cntlr_v4_0_27
vlib modelsim_lib/msim/emb_mem_gen_v1_0_11
vlib modelsim_lib/msim/axi_lite_ipif_v3_0_4
vlib modelsim_lib/msim/mdm_v3_2_29
vlib modelsim_lib/msim/clk_gen_sim_v1_0_6

vmap xilinx_vip modelsim_lib/msim/xilinx_vip
vmap xpm modelsim_lib/msim/xpm
vmap microblaze_v11_0_16 modelsim_lib/msim/microblaze_v11_0_16
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap noc_nmu_sim_v1_0_0 modelsim_lib/msim/noc_nmu_sim_v1_0_0
vmap noc_hbm_nmu_sim_v1_0_0 modelsim_lib/msim/noc_hbm_nmu_sim_v1_0_0
vmap xlconstant_v1_1_10 modelsim_lib/msim/xlconstant_v1_1_10
vmap proc_sys_reset_v5_0_17 modelsim_lib/msim/proc_sys_reset_v5_0_17
vmap smartconnect_v1_0 modelsim_lib/msim/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 modelsim_lib/msim/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_36 modelsim_lib/msim/axi_register_slice_v2_1_36
vmap axi_vip_v1_1_22 modelsim_lib/msim/axi_vip_v1_1_22
vmap axi_apb_bridge_v3_0_21 modelsim_lib/msim/axi_apb_bridge_v3_0_21
vmap versal_cips_ps_vip_v1_0_14 modelsim_lib/msim/versal_cips_ps_vip_v1_0_14
vmap cpm4_v1_0_20 modelsim_lib/msim/cpm4_v1_0_20
vmap cpm5_v1_0_20 modelsim_lib/msim/cpm5_v1_0_20
vmap lmb_v10_v3_0_16 modelsim_lib/msim/lmb_v10_v3_0_16
vmap lmb_bram_if_cntlr_v4_0_27 modelsim_lib/msim/lmb_bram_if_cntlr_v4_0_27
vmap emb_mem_gen_v1_0_11 modelsim_lib/msim/emb_mem_gen_v1_0_11
vmap axi_lite_ipif_v3_0_4 modelsim_lib/msim/axi_lite_ipif_v3_0_4
vmap mdm_v3_2_29 modelsim_lib/msim/mdm_v3_2_29
vmap clk_gen_sim_v1_0_6 modelsim_lib/msim/clk_gen_sim_v1_0_6

vlog -work xilinx_vip -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"/home/smartscott/AMD/2025.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/home/smartscott/AMD/2025.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/home/smartscott/AMD/2025.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/home/smartscott/AMD/2025.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/home/smartscott/AMD/2025.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/home/smartscott/AMD/2025.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/home/smartscott/AMD/2025.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/home/smartscott/AMD/2025.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/home/smartscott/AMD/2025.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"/home/smartscott/AMD/2025.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/home/smartscott/AMD/2025.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/home/smartscott/AMD/2025.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93  \
"/home/smartscott/AMD/2025.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work microblaze_v11_0_16 -64 -93  \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/c957/hdl/microblaze_v11_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/design_1/ip/design_1_microblaze_0_0/sim/design_1_microblaze_0_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_tb3d_transcoder_0_0/sim/design_1_tb3d_transcoder_0_0.v" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/sim/bd_8be5.v" \

vlog -work noc_nmu_sim_v1_0_0 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/noc_nmu_sim_v1_0_vl_rfs.sv" \

vlog -work noc_hbm_nmu_sim_v1_0_0 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/noc_hbm_nmu_sim_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/bd_8be5_S05_AXI_nmu_0_top.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/NOC_NMU512_SPP.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/bd_8be5_S05_AXI_nmu_0.sv" \

vlog -work xlconstant_v1_1_10 -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_1/sim/bd_8be5_const_0_0.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/bd_8be5_S03_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/bd_8be5_S03_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm/bd_8be5_S04_AXI_rpu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm/bd_8be5_S04_AXI_rpu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm/bd_8be5_S02_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm/bd_8be5_S02_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm/bd_8be5_S01_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm/bd_8be5_S01_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm/bd_8be5_S00_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm/bd_8be5_S00_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/rtl/bd_8be5_MC0_ddrc_0_phy_wrapper.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/bd_8be5_MC0_ddrc_0_phy_ddr_responder.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/noc_mc_lpddr4_v1_0_phy_xiphy_behav_lp.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/noc_mc_lpddr4_v1_0_dc_lp.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/noc_mc_lpddr4_v1_0_ddrmc_wdb.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/noc_mc_lpddr4_v1_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model/lpddr4_model.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model/lpddr4_model_wrapper.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na/noc_na_v1_0_vl_rfs.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/bfm/bd_8be5_MC0_ddrc_0_phy.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/rtl/bd_8be5_MC0_ddrc_0_wrapper.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/rtl/bd_8be5_MC0_ddrc_0.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/sim/design_1_axi_noc_0_0.v" \

vcom -work proc_sys_reset_v5_0_17 -64 -93  \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/3d9a/hdl/sc_mmu_v1_0_vl_rfs.sv" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/7785/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/3051/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vcom -work smartconnect_v1_0 -64 -93  \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.vhd" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.sv" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/sc_node_v1_0_vl_rfs.sv" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/0848/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/852f/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/fca9/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/e44a/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work axi_infrastructure_v1_1_0 -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_36 -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/bc4b/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_22 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/b16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vcom -work axi_apb_bridge_v3_0_21 -64 -93  \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/6670/hdl/axi_apb_bridge_v3_0_vh_rfs.vhd" \

vcom -work versal_cips_ps_vip_v1_0_14 -64 -93  \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl/versal_cips_ps_vip_v1_0_rfs.vhd" \

vlog -work versal_cips_ps_vip_v1_0_14 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl/versal_cips_ps_vip_v1_0_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/ip_0/sim/versal_cips_ps_vip_0.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/hdl/pspmc_v1_4_7_sim.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/sim/bd_70da_pspmc_0_0.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/sim/bd_70da.v" \

vlog -work cpm4_v1_0_20 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/cpm4_v1_0_vl_rfs.sv" \

vlog -work cpm5_v1_0_20 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/cpm5_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/sim/design_1_versal_cips_0_0.sv" \

vcom -work lmb_v10_v3_0_16 -64 -93  \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/dac4/hdl/lmb_v10_v3_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/design_1/ip/design_1_dlmb_v10_0/sim/design_1_dlmb_v10_0.vhd" \
"../../../bd/design_1/ip/design_1_ilmb_v10_0/sim/design_1_ilmb_v10_0.vhd" \

vcom -work lmb_bram_if_cntlr_v4_0_27 -64 -93  \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/7cd0/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/sim/design_1_dlmb_bram_if_cntlr_0.vhd" \
"../../../bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/sim/design_1_ilmb_bram_if_cntlr_0.vhd" \

vlog -work emb_mem_gen_v1_0_11 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/0f67/hdl/emb_mem_gen_v1_0_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_lmb_bram_0/sim/design_1_lmb_bram_0.sv" \

vcom -work axi_lite_ipif_v3_0_4 -64 -93  \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work mdm_v3_2_29 -64 -93  \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/1dd0/hdl/mdm_v3_2_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/design_1/ip/design_1_mdm_1_0/sim/design_1_mdm_1_0.vhd" \
"../../../bd/design_1/ip/design_1_rst_noc_clk_gen_300M_0/sim/design_1_rst_noc_clk_gen_300M_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_structure.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_MBUFGCE_CE_DLY.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_cmt_dpll_fd_cal.sv" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_Synchronizer3.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clk_wiz_top.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/sim/design_1_clk_wiz_0.v" \

vlog -work clk_gen_sim_v1_0_6 -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../../tb3d.gen/sources_1/bd/design_1/ipshared/6aeb/hdl/clk_gen_sim_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L noc_nps_v1_0_2 -L axi_vip_v1_1_22 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_14 -L clk_gen_sim_v1_0_6 -L cpm5_v1_0_20 -L cpm4_v1_0_20 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L emb_mem_gen_v1_0_11 -L xilinx_vip "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_clk_gen_1/hdl/design_1_noc_clk_gen_1.sv" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/design_1/ip/design_1_rst_clk_wiz_100M_1/sim/design_1_rst_clk_wiz_100M_1.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../../../AMD/2025.2/data/rsb/busdef" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4/tb/lpddr4_model" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/lpddr4" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../tb3d.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/ip_0" "+incdir+/home/smartscott/AMD/2025.2/data/xilinx_vip/include" \
"../../../bd/design_1/sim/design_1.v" \

vlog -work xil_defaultlib \
"glbl.v"

